Web/Controllers/PasserCommandesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models.Context;
using Models.Dao;

namespace Web.Controllers
{
    public class PasserCommandesController : Controller
    {
        private readonly StiveContext _context;

        public PasserCommandesController(StiveContext context)
        {
            _context = context;
        }

        // GET: PasserCommandes
        public async Task<IActionResult> Index()
        {
            var stiveContext = _context.MouvementStock.Include(m => m.Produit);
            return View(await stiveContext.ToListAsync());
        }

        // GET: PasserCommandes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mouvementStock = await _context.MouvementStock
                .Include(m => m.Produit)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mouvementStock == null)
            {
                return NotFound();
            }

            return View(mouvementStock);
        }

        // GET: PasserCommandes/Create
        public IActionResult Create()
        {
            ViewData["ProduitId"] = new SelectList(_context.Produit, "Id", "Description");
            return View();
        }

        // POST: PasserCommandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NumeroMouvement,Date,Quantite,Remise,Statut,ProduitId")] MouvementStock mouvementStock)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mouvementStock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProduitId"] = new SelectList(_context.Produit, "Id", "Description", mouvementStock.ProduitId);
            return View(mouvementStock);
        }

        // GET: PasserCommandes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mouvementStock = await _context.MouvementStock.FindAsync(id);
            if (mouvementStock == null)
            {
                return NotFound();
            }
            ViewData["ProduitId"] = new SelectList(_context.Produit, "Id", "Description", mouvementStock.ProduitId);
            return View(mouvementStock);
        }

        // POST: PasserCommandes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Quantite,Remise,ProduitId")] MouvementStock mouvementStock)
        {
            if (id != mouvementStock.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mouvementStock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MouvementStockExists(mouvementStock.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProduitId"] = new SelectList(_context.Produit, "Id", "Description", mouvementStock.ProduitId);
            return View(mouvementStock);
        }

        // GET: PasserCommandes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mouvementStock = await _context.MouvementStock
                .Include(m => m.Produit)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mouvementStock == null)
            {
                return NotFound();
            }

            return View(mouvementStock);
        }

        // POST: PasserCommandes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mouvementStock = await _context.MouvementStock.FindAsync(id);
            if (mouvementStock != null)
            {
                _context.MouvementStock.Remove(mouvementStock);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MouvementStockExists(int id)
        {
            return _context.MouvementStock.Any(e => e.Id == id);
        }
    }
}

Web/Controllers/ProduitsController.cs
using Microsoft.AspNetCore.Mvc;
using Models.Dto;
using Newtonsoft.Json;
using System.Net;

namespace Web.Controllers;

public class ProduitsController : Controller
{
    private const string baseAddress = "https://localhost:7080/";
    private static HttpClient? client = null;
    private static CookieContainer cookieContainer = new();
    private static HttpClient Client
    {
        get
        {
            if (client == null)
            {
                client = new() { BaseAddress = new Uri(baseAddress) };
            }
            return client;
        }
    }

    // Récupération des produits via l'API
    public static async Task<List<ProduitLightDto>> GetProduitLights()
    {
        string uri = "api/Produits";
        var response = await Client.GetAsync(uri);
        if (response.IsSuccessStatusCode)
        {
            string result = await response.Content.ReadAsStringAsync();
            return JsonConvert.DeserializeObject<List<ProduitLightDto>>(result) ?? throw new FormatException($"Erreur Http : {uri}");
        }
        throw new Exception(response.ReasonPhrase);
    }

    // Action
    public async Task<IActionResult> Index()
    {
        return View(await GetProduitLights());
    }

    public static async Task<ProduitDto> GetProduitById(int produitId)
    {
        string route = $"api/Produits/{produitId}";
        var response = await Client.GetAsync(route);
        if (response.IsSuccessStatusCode)
        {
            string resultat = await response.Content.ReadAsStringAsync();
            return JsonConvert.DeserializeObject<ProduitDto>(resultat)
                ?? throw new FormatException($"Erreur http : {route} ");
        }
        throw new Exception(response.ReasonPhrase);
    }

    // Action
    public async Task<IActionResult> Details(int Id)
    {
        return View(await GetProduitById(Id));
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/png" href="~/images/favicon.ico">
</head>
<body>
    <header>
        <nav id="navbar" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Produits" asp-action="Index"><img class="logo img-fluid" src="~/images/logo.png" alt="Logo Stive" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produits" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Bienvenue">Bienvenue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PasserCommandes" asp-action="Create">test_Commander</a>
                        </li>
                        @if (User.Identity!.IsAuthenticated)
                        {
                            @* ELEMENTS AFFICHES QUAND UTILISATEUR EST AUTHENTIFIE OK *@
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>